### ISSUE TITLE
Deprecate in favor of rich-model-forms-bundle

### ISSUE THREAD

**Issue by ostrolucky** [Elao/FormSimpleObjectMapper#6]
Following bundle does same thing as this library (and more), doesn't it?

https://github.com/sensiolabs-de/rich-model-forms-bundle

It's endorsed by symfony maintainers on conferences and PHP meetups. Could make sense to deprecate this in favor of it, or link to it.

**Comment by ogizanagi** [comment]
Hi @ostrolucky 

You're right, the mentioned bundle provides the same feature (using the `factory` option with a callable) and more, so I marked as abandoned this package in favor of using `sensiolabs-de/rich-model-forms-bundle`.

Thanks for the notif'!
